require('user.lspconfig.typescript')
require('user.lspconfig.python')
require('user.lspconfig.jsonls')
require('user.lspconfig.ls_emmet')
require('user.lspconfig.rust')
require('user.lspconfig.lua')
require('user.lspconfig.odoo-lsp')
require('user.lspconfig.gopls')
